elevate/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from home.views import *

# handler404 = 'home.views.error_404'
# handler500 = 'home.views.custom_error_view'
# handler403 = 'home.views.custom_error_view'
# handler400 = 'home.views.custom_error_view'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('home.urls')),
]

home/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *


urlpatterns = [
#     path('', home, name='home'),
#     path('buy/', buyMaterial, name='buy'),\
#     path('manufacture/', manufacture, name='manufacture'),
#     path('trade/', send_req, name='trade'),
#     path('accept/<int:pk>/', accept_req, name='accept'),
#     path('reject/<int:pk>/', reject_req, name='reject'),
#     path('delete/<int:pk>/', delete_req, name='delete'),
#     path('test/', test, name='test'),
#     path('get-req/ajax/', pending_req, name='get-req'),
#     path('get-quan/ajax/', get_quantity, name='get-quan'),
#     path('buy/ajax/', get_rmc, name='get-rmc'),
#     path('sellus/', sell_us, name='sellus'),
#     path('category/', cat, name='category'),
#     path('instruction/', instruction, name='instruction'),
]

home/models.py
from django.db import models

# Create your models here.
class Item(models.Model): #Raw materials + product
    name = models.CharField(max_length=50)
    product = models.BooleanField(default=False)
    raw_material = models.BooleanField(default=False)
    product_cost = models.IntegerField(default=0)
    raw_material_cost = models.IntegerField(default=0)
    category_1 = models.BooleanField(default=False)
    category_2 = models.BooleanField(default=False)
    category_3 = models.BooleanField(default=False)

    def __str__(self):
        return self.name

class Spot(models.Model):
    name = models.CharField(max_length=50)
    tax = models.IntegerField(default=0)
    lat = models.CharField(max_length=50, default='0')
    lng = models.CharField(max_length=50, default='0')
    def __str__(self):
        return self.name 

class SpotRawMaterial(models.Model):
    spot = models.ForeignKey(Spot, on_delete=models.CASCADE)
    raw_material = models.ForeignKey(Item, limit_choices_to={'raw_material':True}, on_delete=models.CASCADE, null=True, blank=True)
    quantity = models.IntegerField(default=0)
    cost = models.IntegerField(default=0)
    is_active    = models.BooleanField(default=True)

    def __str__(self):
        return str(self.spot.name) + " - " + str(self.raw_material.name)     

class Industry(models.Model):
    name = models.CharField(max_length=50)
    spot = models.ForeignKey(Spot, on_delete=models.SET_NULL, null=True, blank=True)
    number = models.IntegerField(default=0)

    def __str__(self):
        return self.name

class Route(models.Model):
    from_spot = models.ForeignKey(Spot, related_name="From", on_delete=models.CASCADE)
    to_spot   = models.ForeignKey(Spot, related_name="To", on_delete=models.CASCADE)
    distace   = models.IntegerField()

    def __str__(self):
        return str(self.from_spot) + " -> " + str(self.to_spot) + " = " + str(self.distace)


class Manufacture(models.Model):
    product = models.ForeignKey(Item, related_name='Product', limit_choices_to={'product':True}, on_delete=models.SET_NULL, null=True, blank=True)
    raw_material = models.ForeignKey(Item, related_name='RawMaterial', limit_choices_to={'raw_material':True}, on_delete=models.SET_NULL, null=True, blank=True)
    quantity = models.IntegerField()

    def __str__(self):
        return str(self.product) + " -> " + str(self.raw_material) + " = " + str(self.quantity)


class Notification(models.Model):

    notice = models.CharField(max_length=500)
    def __str__(self):
        return self.notice


class Season(models.Model):
    season_1 = models.BooleanField(default=False)
    season_2 = models.BooleanField(default=False)
    season_3 = models.BooleanField(default=False)
    season_4 = models.BooleanField(default=False)

user/models.py
from django.db import models
from phonenumber_field.modelfields import PhoneNumberField
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.base_user import BaseUserManager
from django.core.validators import MinValueValidator, MaxValueValidator
from home.models import *

class CustomUserManager(BaseUserManager):
    def create_superuser(self, team_name, password=None):
        team = self.model(team_name=team_name, is_staff=True, is_superuser=True)
        team.set_password(password)
        team.save()
        return team



class Team(AbstractUser):
	"""docstring for User"""
	username			= None
	team_name			= models.CharField(max_length=50, unique=True)
	email1 				= models.EmailField(verbose_name='Email Address', unique=True, null=False, blank=False)
	name1 				= models.CharField(max_length=50)
	contact_no1 		= PhoneNumberField(blank=False, null=False, help_text='Add country code before the contact no.')
	email2 				= models.EmailField(verbose_name='Email Address', unique=True, null=False, blank=False)
	name2 				= models.CharField(max_length=50)
	contact_no2 		= PhoneNumberField(blank=False, null=False, help_text='Add country code before the contact no.')
	email3 				= models.EmailField(verbose_name='Email Address', null=True, blank=True)
	name3 				= models.CharField(max_length=50, null=True, blank=True)
	contact_no3 		= PhoneNumberField(blank=True, null=True, help_text='Add country code before the contact no.')
	email4 				= models.EmailField(verbose_name='Email Address', null=True, blank=True)
	name4 				= models.CharField(max_length=50, null=True, blank=True)
	contact_no4 		= PhoneNumberField(blank=True, null=True, help_text='Add country code before the contact no.')
	industry			= models.ForeignKey(Industry, on_delete=models.SET_NULL, null=True, blank=True)
	ecoins				= models.IntegerField(default=1000)

	USERNAME_FIELD 		= 'team_name'
	user_permissions 	= None
	groups 				= None
	REQUIRED_FIELDS 	= []

	objects = CustomUserManager()

	def __str__(self):
		return self.team_name


class RawMaterialCart(models.Model):
	team_name = models.ForeignKey(Team, on_delete=models.CASCADE)
	spot = models.ForeignKey(Spot, verbose_name="Location", on_delete=models.PROTECT, null=True, blank=True)
	raw_material = models.ForeignKey(Item, limit_choices_to={'raw_material':True} ,on_delete=models.CASCADE)
	quantity = models.IntegerField(default=0)

	def __str__(self):
		return str(self.team_name) + " -> " + str(self.raw_material.name)

class RawMaterialBuy(models.Model):
	team_name = models.ForeignKey(Team, on_delete=models.CASCADE)
	spot = models.ForeignKey(Spot, on_delete=models.PROTECT, null=True, blank=True)
	raw_material_1 = models.ForeignKey(Item, related_name="RawMaterial1", limit_choices_to={'raw_material':True} ,on_delete=models.CASCADE)
	quantity_1 = models.IntegerField(default=0)
	raw_material_2 = models.ForeignKey(Item, related_name="RawMaterial2", limit_choices_to={'raw_material':True} ,on_delete=models.CASCADE)
	quantity_2 = models.IntegerField(default=0)
	raw_material_3 = models.ForeignKey(Item, related_name="RawMaterial3", limit_choices_to={'raw_material':True}, on_delete = models.CASCADE, null=True, blank=True)
	quantity_3 = models.IntegerField(default=0, null=True, blank=True)
	raw_material_4 = models.ForeignKey(Item, related_name="RawMaterial4", limit_choices_to={'raw_material':True}, on_delete = models.CASCADE, null=True, blank=True)
	quantity_4 = models.IntegerField(default=0, null=True, blank=True)

	def __str__(self):
		return str(self.team_name) + " -> " + str(self.raw_material_1.name) + " and " + str(self.raw_material_2.name) 

class ProductCart(models.Model):
	team_name = models.ForeignKey(Team, on_delete=models.CASCADE)
	product = models.ForeignKey(Item, limit_choices_to={'product':True}, on_delete=models.CASCADE)
	quantity = models.IntegerField(default=0)

	def __str__(self):
		return str(self.team_name) + " -> " + str(self.product.name)

class SendRequest(models.Model):
	from_team = models.ForeignKey(Team, related_name="FromTeam", on_delete=models.CASCADE)
	to_team = models.ForeignKey(Team, related_name="ToTeam", on_delete=models.CASCADE)
	item = models.ForeignKey(Item, on_delete=models.CASCADE)
	cost = models.IntegerField(verbose_name="Cost Per Unit")
	quantity = models.IntegerField()
	is_accepted = models.BooleanField(default=False)
	is_visible = models.BooleanField(default=False)

	def __str__(self):
		return str(self.from_team.team_name) + " -> " + str(self.to_team.team_name)


class SellUs(models.Model):
	team = models.ForeignKey(Team, on_delete=models.PROTECT)
	item = models.ForeignKey(Item, on_delete=models.CASCADE, null=True, blank=True)
	quantity = models.IntegerField()

home/forms.py
from django import forms
from user.models import *
from .models import *

class IndustryForm(forms.ModelForm):
    class Meta():
        model 		= Team
        fields 		= ['industry']

class BuyRawMaterialForm(forms.ModelForm):
    class Meta():
        model       = RawMaterialBuy
        fields      = ['spot', 'raw_material_1', 'quantity_1', 'raw_material_2', 'quantity_2', 'raw_material_3', 'quantity_3', 'raw_material_4', 'quantity_4']


class ManufactureForm(forms.ModelForm):
    class Meta():
        model       = ProductCart
        fields      = ['product', 'quantity']

class SendRequestForm(forms.ModelForm):
    class Meta():
        model       = SendRequest
        fields      = ['to_team', 'item', 'cost', 'quantity']

class SellUsForm(forms.ModelForm):
    class Meta():
        model       = SellUs
        fields      = ['item', 'quantity']

home/templates/home/buying-2.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOME</title>
</head>
<body>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <h1>HOME PAGE</h1>
    <form method="POST" id="buying-form">
        {% csrf_token %}
        {{form|crispy}}
        <br>
        <input type="button" id="submit-btn" value="submit">
    </form>
    <br>
    {% for spot in spots %}
        <h2>{{spot.name}}-></h2>
        {% for i in spr %}
            {% if spot.name == i.spot.name %}
                <p>Name: {{i.raw_material.name}}</p>
                <p id="{{i.id}}">Quantity: {{i.quantity}}</p>
                <p>Cost: {{i.cost}}</p>
            {% endif %}
        {% endfor %}
    {% endfor %}
</body>
<script
  src="https://code.jquery.com/jquery-3.1.1.min.js"></script>

<script>
    $(document).ready(function(){
        $('#submit-btn').click(function(){
        console.log('hello world')
        let spot = $('#id_spot').val();
        let raw_material_1 = $('#id_raw_material_1').val();
        let raw_material_2 = $('#id_raw_material_2').val();
        let quantity_1 = $('#id_quantity_1').val();
        let quantity_2 = $('#id_quantity_2').val();
        let token = $('input[name=csrfmiddlewaretoken]').val();
        // console.log(spot, rm1, rm2, q1, q2)
        mydata = {"spot":spot, "raw_material_1":raw_material_1, "raw_material_2":raw_material_2, "quantity_1":quantity_1, "quantity_2":quantity_2, "csrfmiddlewaretoken": token}
        console.log(mydata)
        $.ajax({
            type: "POST",
            url: "/buy/",
            data: mydata,
            dataType: "json",
            success:function(res){
                for(i=0; i<res.spr.length; i++){
                    $('#' + res.spr[i].id).html('Quantity' + res.spr[i].quantity);
                }
                if (res.messages){
                    for (i in res.messages)
                        alert(res.messages[i]);
                }
            }
        });
    });
    });
    
</script>
    
</html>

home/templates/home/home.html
{% load crispy_forms_tags %} {% load static %}
<!DOCTYPE html>
<html>


<meta http-equiv="content-type" content="text/html;charset=utf-8" />
<!-- /Added by HTTrack -->

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>ELEVATE 2.0</title>
    <!-- Canonical SEO -->
    <link rel="canonical" href="https://www.creative-tim.com/product/argon-dashboard" />
    <!-- Favicon -->
    <link rel="icon" href="{% static 'home/assets/img/favicon.ico' %}">
    <!-- Fonts -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700">
    <!-- Icons -->
    <link rel="stylesheet" href="{% static 'home/assets/vendor/nucleo/css/nucleo.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'home/assets/vendor/%40fortawesome/fontawesome-free/css/all.min.css' %}" type="text/css">
    <!-- Argon CSS -->
    <link rel="stylesheet" href="{% static 'home/assets/css/argon.min5438.css?v=1.2.0' %}" type="text/css">

</head>

<body>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}" {% endif %}>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %} {{ message }}
            </li>
            {% endfor %}
    </ul>
    {% endif %}
    <div class="header py-4 py-lg-3 pt-lg-9">
        <div class="container">
            <div class="header-body text-center mb-7">
                <div class="row justify-content-center">
                </div>
            </div>
        </div>
    </div>

    <!-- Page content -->
    <div class="container mt--8 pb-5">
        <div class="row justify-content-center">
            <div class="col-lg-5 col-md-7">
                <div class="card bg-secondary border-0 mb-0">
                    <div class="card-header bg-transparent pb-0">
                        <div class="text-light text-center">
                            <h3> Choose your industry</h3>
                        </div>
                    </div>
                    <div class="card-body px-lg-5 py-lg-5">
                        {% if user.industry == None %}
                        <form role="form" method="POST">
                            {% csrf_token %} {{form | crispy}}

                            <div class="text-center">
                                <input type="submit" value="Start Game" class="btn btn-primary my-4">
                            </div>
                        </form>
                        {% else %}
                        <div class="text-light text-center">
                            <h3>You have successfully choosen your Industry. You can start the game now.</h3>
                            <div class="text-center">
                                <a href="{% url 'buy' %}" class="btn btn-primary my-4">Start Game</a>
                            </div>
                        </div>
                        {% endif%}
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Core -->
    <script src="{% static 'home/assets/vendor/jquery/dist/jquery.min.js' %}"></script>


    <script src="{% static 'home/assets/vendor/bootstrap/dist/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'home/assets/vendor/js-cookie/js.cookie.js' %}"></script>
    <script src="{% static 'home/assets/vendor/jquery.scrollbar/jquery.scrollbar.min.js' %}"></script>
    <script src="{% static 'home/assets/vendor/jquery-scroll-lock/dist/jquery-scrollLock.min.js' %}"></script>
    <!-- Argon JS -->
    <script src="{% static 'home/assets/js/argon.min5438.js?v=1.2.0' %}"></script>
</body>


</html>

home/templates/home/manufacture-2.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOME</title>
</head>
<body>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <h1>Manufacture PAGE</h1>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="submit">
    </form>
</body>
</html>

home/templates/home/sellus.html
{% extends "home/base.html" %} {% load static %} {% load crispy_forms_tags %} {% block head %}{% endblock head %} {% block bodytag %}{% endblock bodytag %} {% block sidenav %}
<nav class="sidenav navbar navbar-vertical  fixed-left  navbar-expand-xs navbar-light bg-white" id="sidenav-main">
    <div class="scrollbar-inner">
        <!-- Brand -->
        <div class="sidenav-header  align-items-center">
            <img src="{% static 'home/assets/img/elevate-black.png' %}" style="height: 100px; width: 100px; margin-top: 5px;">

        </div>
        <div class="navbar-inner">
            <!-- Collapse -->
            <div class="collapse navbar-collapse" id="sidenav-collapse-main">
                <div class="col-xl-4" style="margin-top: 40px;">
                    <h2 class="mb-0" style="color: black !important;">Industry</h2>
                </div>

                <!-- Nav items -->
                <ul class="navbar-nav" id="resource-inventory">
                    <li class="nav-item">
                        <div class="nav-link" style="padding: 0.675rem 1.5rem;">
                            <!--<i class="ni ni-tv-2 text-primary"></i>-->
                            <span class="nav-link-text">{{request.user.industry.spot.name}}</span>
                        </div>
                    </li>
                </ul>
                <hr class="my-3">
                <div class="col-xl-4">
                    <h2 class="mb-0" style="color: black !important;">Raw Materials</h2>
                </div>

                <!-- Nav items -->
                <ul class="navbar-nav">
                    {% for i in rmc %}
                    <li class="nav-item">
                        <a class="nav-link" href="#">
                            <!--<i class="ni ni-tv-2 text-primary"></i>-->
                            <span class="nav-link-text">{{i.raw_material}}</span><span class="lak" id="{{i.id}}rmc">{{i.quantity}}</span>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
                <!-- Divider -->
                <hr class="my-3">
                <!-- Heading-->
                <div class="col-xl-4">
                    <h2 class="mb-0" style="color: black !important;">Products</h2>
                </div>
                <ul class="navbar-nav mb-md-3">
                    {% for i in pc%}
                    <li class="nav-item">
                        <a class="nav-link" href="#" target="_blank">
                            <!--<i class="ni ni-spaceship"></i>-->
                            <span class="nav-link-text">{{i.product}}</span><span class="lak" id="{{i.id}}pc">{{i.quantity}}</span>
                        </a>
                    </li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</nav>
{% endblock sidenav %} {% block body %}
<div class="container-fluid">
    <div class="row" style="justify-content: center;">
        <div class="col-xl-4">
            <div class="card">
                <div class="table-responsive">

                    <table class="table align-items-center table-flush" style="color: white;">
                        <thead class="thead-light" style="color: black !important">
                            <div class="card-header" style="background: #353535">
                                <h2 style="font-weight: bold;">Raw Material Price</h2>
                            </div>
                            <tr>
                                <th scope="col" style="color: black !important; font-weight: bold;">RAW MATERIALS</th>

                                <th scope="col" style="color: black !important; font-weight: bold;">PRICE</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for r in rmcost %}
                            <tr>
                                <th scope="row">{{r.name}}</th>
                                <td>
                                    {{r.raw_material_cost}}

                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-xl-4">
            <div class="card">
                <div class="table-responsive">
                    <!-- Projects table -->

                    <table class="table align-items-center table-flush" style="color: white;">
                        <thead class="thead-light">
                            <div class="card-header" style="background: #353535">
                                <h2 style="font-weight: bold;">Product Price</h2>
                            </div>
                            <tr>
                                <th scope="col" style="color: black !important; font-weight: bold;">PRODUCTS</th>

                                <th scope="col" style="color: black !important; font-weight: bold;">PRICE</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for p in pcost %}
                            <tr>
                                <th scope="row">{{p.name}}</th>
                                <td>
                                    {{p.product_cost}}
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-xl-4">
            <div class="card">
                <div class="card-header" style="background: #353535">
                    <h2 style="font-weight: bold;">Sell Us</h2>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %} {{form|crispy}}
                        <div class="text-center">
                            <input type="button" id="submit-btns" value="Sell" class="btn btn-primary my-4">
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>


{% endblock body %} {% block js%}
<script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
<script>
    $(document).ready(function() {
        $('#submit-btns').click(function() {
            let item = $('#id_item').val();
            let quantity = $('#id_quantity').val();
            let token = $('input[name=csrfmiddlewaretoken]').val();
            $("#submit-btns").val("Processing...");
            $("#submit-btns").attr('disabled', true);
            mydata = {
                "item": item,
                "quantity": quantity,
                "csrfmiddlewaretoken": token
            }
            console.log(mydata)
            $.ajax({
                type: "POST",
                url: "/sellus/",
                data: mydata,
                dataType: "json",
                success: function(res) {
                    $('#ecoins').html(res.ecoin)
                    for (i = 0; i < res.rmc.length; i++) {
                        $('#' + res.rmc[i].id + 'rmc').html(res.rmc[i].quantity);
                    }
                    for (i = 0; i < res.pc.length; i++) {
                        $('#' + res.pc[i].id + 'pc').html(res.pc[i].quantity);
                    }
                    if (res.messages) {
                        for (i in res.messages)
                            alert(res.messages[i]);
                    }
                    $("#submit-btns").val("Sell");
                    $("#submit-btns").attr('disabled', true);
                    $("form")[0].reset()
                }
            });
        });
    });
</script>

{% endblock js%}

home/templates/home/trading.html
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOME</title>
</head>
<body>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <h1>Trade PAGE</h1>
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit" value="submit">
    </form>
    {% if req %}
        <h1>Received Request</h1>
        {% for r in req %}
            <h3>From Team: {{r.from_team}}</h3>
            <h3>Product Name: {{r.item}}</h3>
            <h3>Quantity: {{r.quantity}}</h3>
            <h3>Cost: {{r.cost}}</h3>
            <a href="{% url 'accept' r.id %}">Accept Request</a>
            <br><br>
        {% endfor %}
    {% endif %}
</body>
</html>